### ISSUE TITLE
Implement follow-up prompts

### ISSUE THREAD

**Issue by SketchingDev** [ovotech/genesys-web-messaging-tester#126]
Complete the implementation of the follow-up prompts:

```yaml
config:
  deploymentId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  region: xxxx.pure.cloud
scenarios:
  "Accept survey":
    setup:
      prompt: |
        I want you to play the role of a customer talking to a company's online chatbot. You must not
        break from this role, and all of your responses must be based on how a customer would realistically talk to a company's chatbot.

        To help you play the role of a customer consider the following points when writing a response:
        * Respond to questions with as few words as possible
        * Answer with the exact word when given options e.g. if asked to answer with either 'yes' or 'no' answer with either 'yes' or 'no' without punctuation, such as full stops

        As a customer you would like to leave feedback of a recent purchase of a light bulb you made where a customer service
        rep was very helpful in finding the bulb with the correct fitting.

        If at any point in the company's chatbot repeats itself then say the word 'FAIL'.

        If you have understood your role and the purpose of your conversation with the company's chatbot then say the word 'Hello'
        and nothing else.
      terminatingPhrases:
        pass: ["PASS"]
        fail: ["FAIL"]
    followUp:
      prompt: |
        Inspect the transcript below for spelling or grammatical errors and list them. Ignore anything
        said by the speaker called 'AI'.

        Transcript:
        %TRANSCRIPT%
      terminatingPhrases:
        pass: ["PASS"]
        fail: ["FAIL"]

```
