### ISSUE TITLE
Use ChatGPT as assertion to reduce test fragility

### ISSUE THREAD

**Issue by SketchingDev** [ovotech/genesys-web-messaging-tester#35]
Integrate ChatGPT into test scenarios to allow more forgiving assertions, reducing fragility of tests.

Example of possible assertion function `aiWaitFor`:

```yaml
config:
  deploymentId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  region: xxxx.pure.cloud
scenarios:
  "Asked for account ID":
    - say: hi
    - aiWaitFor: a request for my account number
    - say: 12345
    - aiWaitFor: a message thanking me for my account number, and asking me to wait whilst it is checked
```

Example prompt:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/31957045/229492580-4af8428d-a850-4734-9f22-2f837da1069c.png">
