### ISSUE TITLE
Use ChatGPT to navigate a customer journey

### ISSUE THREAD

**Issue by SketchingDev** [ovotech/genesys-web-messaging-tester#36]
Add the ability for a test to utilise ChatGPT to navigate a customer journey.

Why:
* It would remove the complexity of navigating complex flows using expected responses 
* Theoretically journeys could be heavily modified without the tests needing to change  

Below is an example of what the scenario might look like, with `aiHaveConversationAbout` being the operator for indicating you want ChatGPT to have a conversion:
```yaml
config:
  deploymentId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  region: xxxx.pure.cloud
scenarios:
  "Negative survey responses end with offer to talk to an agent":
    - aiHaveConversationAbout: a product that you're not satisfied with. You've just connected to their customer service chat-bot and will tell it you want to submit a feedback questionnaire, which you will fill in with your experience.
    # ChatGPT will then have the conversation and only quit when the following assertion is matched
    - waitForReplyContaining: Sorry to hear about your experience with us. Would you like to speak to an agent?
```
