### ISSUE TITLE
Allow multiple scenarios per test config

### ISSUE THREAD

**Issue by tarlingovo** [ovotech/genesys-web-messaging-tester#47]
Could we re-use one deployment configuration for more than one scenario file? This might reduce a bit of overhead

e.g.

As well as

```
  - name: Deployment Config Name
    deploymentFlow: Inbound message flow name
    deploymentConfig: Messenger Deployment Config Name
    scenarios: scenario.yaml
 ```

Can we also support the following?

```
  - name: Deployment Config Name
    deploymentFlow: Inbound message flow name
    deploymentConfig: Messenger Deployment Config Name
    scenarios:
      - scenario-1.yaml
      - scenario-2.yaml
 ```
